### ISSUE TITLE
Add Any Field Type

### ISSUE THREAD

**Issue by kouliavtsev** [contentlayerdev/contentlayer#331]
In contentlayer `2.7`, the string definition would work like `any`, after the upgrade to `2.8` if the data is not a string an error is thrown. This is correct behavior, yet if you are not able to change the data source you are stuck using contentlayer `2.7`.

A good example would be a `yaml` config file with fields `null`, `true`, `some string`, etc.

```js
// ...
defaultValue: {
  type: "any",
},
```

```yml
# item 1
defaultValue: null
# item 2
defaultValue: true
# item 3
defaultValue: some string
```

Even though, using `any` looks like introducing an anti-pattern. I think it has a viable use case. 

Similarly, the [Add Union Field Type](https://github.com/contentlayerdev/contentlayer/issues/250) could solve this problem. Yet, it seems a bit harder to implement.
