### ISSUE TITLE
YAMLParseError occurs with CRLF document endings followed by a quotation mark or similar characters

### ISSUE THREAD

**Issue by Mona04** [contentlayerdev/contentlayer#543]
```
---
title: "If it ends with a quotation mark, it doesn't work."
---
## ...
```

A document like the above throws the YAMLParseError when CRLF is used. 
It is because gray-matter gives the custom YAML engine a string that ends with '\r'. 

The problem can be easily resolved by a simple check on the last character, like below.

```
matter(markdownString, {
        engines: {
          // Provide custom YAML engine to avoid parsing of date values https://github.com/jonschlinkert/gray-matter/issues/62)
          yaml: (str) => {
            if(str.length > 0 && str[str.length-1] == '\r'){
              str = str.slice(0, str.length-1);
            }
            return yaml.parse(str)
          }
        },
      }),
``` 
line 223 in "/node_modules/@contentlayer/source-files/src/fetchData/makeCacheItemFromFilePath.ts"

So, I'm wondering whether the issue mentioned above would be addressed in future versions, 
or should I make all my documents use LF instead of CRLF?

**Comment by suchcodewow** [comment]
I ran into same thing.  Is there an option to add the above check to contentlayer.config.js?

**Comment by pavlovtech** [comment]
I'm having the same issue on Windows. 

Error example:

```
   • "posts/top-10-insights-about-web-app-optimizations.md" failed with YAMLParseError: Unexpected scalar at node end at line 12, column 52:

     slug: 'top-10-insights-about-web-app-optimizations'
```
     
    My YAML:

```
---
publishedAt: '2022-03-21T15:42:12.174Z'
title: 'Top 10 Insights About Web Application Optimization'
featured: no
tags: 'javascrpt, optimization'
coverImage: '/assets/gear.jpg'
description: 'Web application optimization is crucial for any web app. You can improve web application performance with Static Site Generation, modern image formats, lazy image loading, Next.JS and Preact.'
status: 'published'
author:
  name: 'Alex Pavlov '
  picture: 'https://avatars.githubusercontent.com/u/6662454?v=4'
slug: 'top-10-insights-about-web-app-optimizations'
---
```
