### ISSUE TITLE
MDX problem in windows with contentlayer

### ISSUE THREAD

**Issue by VittorioMorellini** [contentlayerdev/contentlayer#591]
Warning: Found 3 problems in 3 documents.

 └── Invalid markdown in 3 documents. (Skipping documents)

     • "blogs/blog-one.mdx" failed with YAMLParseError: Unexpected scalar at node end at line 9, column 29:

     image: '../images/proj1.jpg'
                                 ^

     • "blogs/blog-three.mdx" failed with YAMLParseError: Unexpected scalar at node end at line 9, column 29:

     image: '../images/proj3.jpg'
                                 ^

     • "blogs/blog-two.mdx" failed with YAMLParseError: Unexpected scalar at node end at line 8, column 191:

     …1mZWVkfDMyfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60'

I found this error when I build on windows.

My stack is:

Next.js 13.5.6  (pages dir)
Node 18.18.2
"contentlayer": "^0.3.4",

The source code is available at:
https://github.com/VittorioMorellini/Portfolio

When I deploy on Vercel it works fine.
Can anyone help me?

**Comment by Blankeos** [comment]
Hi @VittorioMorellini! I'm also on windows. Honestly actually probably the same error as I have on: 
- https://github.com/contentlayerdev/contentlayer/issues/594

Wherein Frontmatter YAML parsing fails at the end of the frontmatter for some reason. Thing is, this is a valid YAML actually:
![image](https://github.com/contentlayerdev/contentlayer/assets/38070918/fa12bb6d-113d-4eb6-bed3-efb723ac2a26)

### Here's a workaround though.

The single quotes aren't actually necessary for your "string" types to parse as "string". I noticed upon removing the single quotes for the last property in the frontmatter, it actually started building the document haha. So maybe just do that.

I only use the quotes when I have actual quotes or ":" within my string
```yaml
description: 'my undergrad thesis: automatic assessment of scoliosis'
```

#### With that said, change your frontmatter to this on `blog-one.mdx`

```yaml
title: 'dotnet Blazor'
publishedAt: 'April 1, 2023'
description: 'Learn how to create an application in Blazor'
#credit: 'Fabio Biondi'
cover: '/optimized/articles/blog-three/hero.webp'
seoDescription: 'This is the for React redux.'
category: 'dotnet'
image: ../images/proj3.jpg
```

![image](https://github.com/contentlayerdev/contentlayer/assets/38070918/cc89c6d7-00fe-4dd5-bcff-3c830550d615)
